In [1]:
import pandas as pd
data = pd.read_csv('datasets/kc_house_data.csv')

#### 1. Qual a  média do preço de compra dos imóveis por “Nível”?
- Nível 0: entre R$\$$ 0,00 e R$\$$ 321.950,00
- Nível 1: entre R$\$$ 321.950,00 e R$\$$ 450.000,00
- Nível 2: entre R$\$$ 450.000,00 e R$\$$ 645.000,00
- Nível 3: Preço acima de R$\$$ 645.000,00

In [2]:
for i in range(len(data)):
    if (data.loc[i, 'price'] >= 0) & (data.loc[i, 'price'] <= 321950):
        data.loc[i, 'nivel'] = 'nivel_0'
    elif (data.loc[i, 'price'] > 321950) & (data.loc[i, 'price'] <= 450000):
        data.loc[i, 'nivel'] = 'nivel_1'
    elif (data.loc[i, 'price'] > 450000) & (data.loc[i, 'price'] <= 645000):
        data.loc[i, 'nivel'] = 'nivel_2'
    else:
        data.loc[i, 'nivel'] = 'nivel_3'
data.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,nivel
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,nivel_0
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,nivel_2
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,770,0,1933,0,98028,47.7379,-122.233,2720,8062,nivel_0
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,nivel_2
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,nivel_2

In [3]:
avg_price_by_nivel = data[['price', 'nivel']].groupby('nivel').mean().reset_index()
avg_price_by_nivel

     nivel          price
0  nivel_0  251557.649889
1  nivel_1  385688.681502
2  nivel_2  539730.960007
3  nivel_3  987540.224456

#### 2. Qual a média do tamanho da sala de estar dos imóveis por "Size"?
- Size 0: Tamanho entre 0 e 1427 sqft
- Size 1: Tamanho entre 1427 e 1910 sqft
- Size 2: Tamanho entre 1910 e 2550 sqft
- Size 3: Tamanho acima de 2550 sqtf

In [4]:
data['size'] = data['sqft_living'].apply(lambda x: 0 if x < 1427 else
                                          1 if (x > 1427) & (x < 1910) else
                                          2 if (x > 1910) & (x < 2550) else 3)
data.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,nivel,size
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,0,1955,0,98178,47.5112,-122.257,1340,5650,nivel_0,0
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,400,1951,1991,98125,47.7210,-122.319,1690,7639,nivel_2,3
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,0,1933,0,98028,47.7379,-122.233,2720,8062,nivel_0,0
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,910,1965,0,98136,47.5208,-122.393,1360,5000,nivel_2,2
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,0,1987,0,98074,47.6168,-122.045,1800,7503,nivel_2,1

In [5]:
avg_sqft_living_by_size = data[['sqft_living', 'size']].groupby('size').mean().reset_index()
avg_sqft_living_by_size

   size  sqft_living
0     0  1123.776421
1     1  1661.241987
2     2  2207.123507
3     3  3297.951224

#### 3. Adicione as seguintes informações ao conjunto de dados original:
- Place ID: Identificação da localização
- OSM type: Open Street Map Type
- Country: Nome do País
- Country Code: Código do País

In [6]:
from geopy.geocoders import Nominatim

In [7]:
# Initialize Nominatim API
geolocator = Nominatim(user_agent='geoapiExercises')

In [8]:
# exemplo teste
response = geolocator.reverse('47.5112,-122.257')
response.raw

{'place_id': 161022547,
 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
 'osm_type': 'way',
 'osm_id': 236673600,
 'lat': '47.5112302',
 'lon': '-122.25676111324441',
 'display_name': '10012, 61st Avenue South, Rainier Beach, Seattle, King County, Washington, 98178, United States',
 'address': {'house_number': '10012',
  'road': '61st Avenue South',
  'neighbourhood': 'Rainier Beach',
  'city': 'Seattle',
  'county': 'King County',
  'state': 'Washington',
  'ISO3166-2-lvl4': 'US-WA',
  'postcode': '98178',
  'country': 'United States',
  'country_code': 'us'},
 'boundingbox': ['47.511189', '47.5112943', '-122.2568571', '-122.2566651']}

In [9]:
# Create empty rows
data['place_id'] = 'NA'
data['osm_type'] = 'NA'
data['country'] = 'NA'
data['country_code'] = 'NA'

In [10]:
geolocator = Nominatim(user_agent='geopiExercises')

for i in range(len(data)):
    if i % 1000 == 0:
        print(f'loop: {i} / {len(data)}')
    query = str(data['lat'][i]) + ',' + str(data['long'][i])
    
    #API Request
    response = geolocator.reverse(query)
    
    #populate data
    if 'place_id' in response.raw:
        data.loc[i, 'place_id'] = response.raw['place_id']
    if 'osm_type' in response.raw:
        data.loc[i, 'osm_type'] = response.raw['osm_type']
    if 'country' in response.raw['address']:
        data.loc[i, 'country'] = response.raw['address']['country']
    if 'country_code' in response.raw['address']:
        data.loc[i, 'country_code'] = response.raw['address']['country_code']

loop: 0 / 21613

KeyboardInterrupt:

In [ ]:
data.to_csv('datasets/kc_house_data2.csv', index=False)

In [9]:
data = pd.read_csv('datasets/kc_house_data2.csv')

In [10]:
data.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,lat,long,sqft_living15,sqft_lot15,nivel,size,place_id,osm_type,country,country_code
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,47.5112,-122.257,1340,5650,nivel_0,0,161022547,way,United States,us
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,47.7210,-122.319,1690,7639,nivel_2,3,337363785,way,United States,us
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,47.7379,-122.233,2720,8062,nivel_0,0,74951055,node,United States,us
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,47.5208,-122.393,1360,5000,nivel_2,2,156726151,way,United States,us
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,47.6168,-122.045,1800,7503,nivel_2,1,296045104,way,United States,us

#### 4. Adicione os seguintes filtros no mapa:
- Tamanho mínimo da área da sala de estar
- Número mínino de banheiros
- Valor máximo do preço
- Tamanho máximo da área do porão
- Filtro das condições do imóvel
- Filtro por ano de construção

In [11]:
import pandas as pd
import plotly.express as px
import ipywidgets as widgets

In [12]:
data = pd.read_csv('datasets/kc_house_data2.csv')

In [13]:
data['is_waterfront'] = data['waterfront'].apply(lambda x: 'yes' if x==1 else 'no')

data['level'] = data['price'].apply(lambda x: 0 if x < 321950 else
                                          1 if (x > 321950) & (x < 450000) else
                                          2 if (x > 450000) & (x < 645000) else 3)
data['level'] = data['level'].astype(int)

In [14]:
# FILTROS #

style = {'description_width': 'initial'}

# Botão interativo de vista para o mar (dropdown)
waterfront_bar = widgets.Dropdown(
    options=data['is_waterfront'].unique().tolist(),
    value='yes',
    description='Water View',
    disable=False)

# 1. Botão interativo do tamanho da sala de estar (slider)
sqft_living_slider = widgets.IntSlider(
    value=data['sqft_living'].min(),
    min=data['sqft_living'].min(),
    max=data['sqft_living'].max(),
    step=1,
    description='Liv Room Min Size',
    dizable=False,
    style=style)

# 2. Botão interativo de número mínino de banheiros (dropdown)
bathrooms_bar = widgets.Dropdown(
    options=sorted(data['bathrooms'].unique().tolist()),
    value=0,
    description='Bathrooms',
    disable=False)

# 3. Botão interativo do preço (slider)
price_slider = widgets.FloatSlider(
    value=data['price'].max(),
    min=data['price'].min(),
    max=data['price'].max(),
    step=1,
    description='Maximum Price',
    dizable=False,
    readout_format='.2f',
    style=style)

# 4. Botão interativo do do tamanho máximo da área do porão (slider)
basement_slider = widgets.IntSlider(
    value=data['sqft_basement'].max(),
    min=data['sqft_basement'].min(),
    max=data['sqft_basement'].max(),
    step=1,
    description='Basement Size',
    dizable=False,
    style=style)

# 5. Filtro das condições do imóvel
condition_button = widgets.ToggleButtons(
    options=sorted(data['condition'].unique()),
    value=3,
    description='Condition:',
    disabled=False,
    style=style)

# 6. Filtro por ano de construção
year_slider = widgets.IntRangeSlider(
    value=[data['yr_built'].min(), data['yr_built'].max()],
    min=data['yr_built'].min(),
    max=data['yr_built'].max(),
    step=1,
    description='Year:',
    disabled=False)

def interact_map(data, waterfront, p_slider, s_sqft_liv, b_bar, base_slider, cond_button, yr_slider):
    houses = data[(data['price'] <= p_slider) &
                  (data['is_waterfront'] == waterfront) &
                  (data['sqft_living'] >= s_sqft_liv) &
                  (data['bathrooms'] >= b_bar) &
                  (data['sqft_basement'] <= base_slider) &
                  (data['condition'] == cond_button) &
                  (data['yr_built'] != yr_slider)]
    [['id', 'lat', 'long', 'price', 'level', 'sqft_living', 'bathrooms', 'sqft_basement', 'condition', 'yr_built']]

    fig = px.scatter_mapbox(houses, lat='lat', lon='long', color='level', size='price',
                           color_continuous_scale=px.colors.cyclical.IceFire,
                           size_max=15, zoom=10)

    fig.update_layout(mapbox_style='open-street-map')
    fig.update_layout(height=600, margin={'r':0, 't':0, 'l':0, 'b':0})
    fig.show()

In [15]:
widgets.interactive(interact_map,
                    data=widgets.fixed(data),
                    waterfront=waterfront_bar,
                    p_slider=price_slider,
                    s_sqft_liv=sqft_living_slider,
                    b_bar=bathrooms_bar,
                    base_slider=basement_slider,
                    cond_button=condition_button, yr_slider=year_slider)

interactive(children=(Dropdown(description='Water View', index=1, options=('no', 'yes'), value='yes'), FloatSl…

#### 5. Adicione os seguintes filtros no Dashboard:
- Filtro por data disponível para compra
- Filtro por ano de renovação
- Filtro se possui vista para água ou não

In [2]:
import pandas as pd
import ipywidgets as widgets
from ipywidgets import fixed
from matplotlib import gridspec
from matplotlib import pyplot as plt

In [12]:
df = pd.read_csv('datasets/kc_house_data2.csv')

# change date format
df['year'] = pd.to_datetime(df['date']).dt.strftime('%Y')
df['date'] = pd.to_datetime(df['date']).dt.strftime('%Y-%m-%d')
df['year_week'] = pd.to_datetime(df['date']).dt.strftime('%Y-%U')

df['is_waterfront'] = df['waterfront'].apply(lambda x: 'yes' if x == 1 else 'no')

# Widgets date
date_limit = widgets.SelectionSlider(
    options=df['date'].sort_values().unique().tolist(),
    value='2014-11-01',
    description='Disponível',
    continuous_update=False,
    orientation='horizontal',
    readout=True)

# Widgets year renovated
year_slider = widgets.SelectionSlider(
    options=df['yr_renovated'].sort_values().unique().tolist(),
    value=1970,
    description='Renovação',
    continuous_update=False,
    orientation='horizontal',
    readout=True)

# Botão interativo de vista para o mar (dropdown)
waterfront_bar = widgets.Dropdown(
    options=df['is_waterfront'].unique().tolist(),
    value='yes',
    description='Water View',
    disable=False)

def update_map(df, limit, year_r, water_f):
    # Filter df
    df = df[(df['date'] >= limit) & (df['yr_renovated'] >= year_r) & (df['is_waterfront'] == water_f)]
    
    
    fig = plt.figure(figsize=(21,12))
    specs = gridspec.GridSpec(ncols=2, nrows=2, figure=fig)
    
    ax1 = fig.add_subplot(specs[0, :])
    ax2 = fig.add_subplot(specs[1, 0])
    ax3 = fig.add_subplot(specs[1, 1])

    by_year = df[['id', 'year']].groupby('year').sum().reset_index()
    ax1.bar(by_year['year'], by_year['id'])

    by_day = df[['id', 'date']].groupby('date').mean().reset_index()
    ax2.plot(by_day['date'], by_day['id'])
    ax2.set_title('Avg Price by Day')
    plt.xticks(rotation=60);
    
    by_week_of_year = df[['id', 'year_week']].groupby('year_week').mean().reset_index()
    ax3.bar(by_week_of_year['year_week'], by_week_of_year['id'])
    ax3.set_title('Avg Price by Week of Year')
    plt.xticks(rotation=60);

In [13]:
widgets.interactive(update_map, df=fixed(df), limit=date_limit, year_r=year_slider, water_f=waterfront_bar)

interactive(children=(SelectionSlider(continuous_update=False, description='Disponível', index=183, options=('…